// lib/mockLiveData.ts
import { LiveStream, ArchivedStream } from "@/types/news";

export const mockLiveStreams: LiveStream[] = [
  {
    id: "live-1",
    title: "گزارش زنده از نشست خبری رئیس جمهور",
    description: "پوشش لحظه به لحظه نشست خبری و پاسخ به سوالات خبرنگاران",
    thumbnail: "/assets/images/png/test.jpg",
    category: "سیاسی",
    categorySlug: "politics",
    startTime: new Date().toISOString(),
    isLive: true,
    viewers: 12450,
  },
  {
    id: "live-2",
    title: "پخش زنده بازی پرسپولیس و استقلال",
    description: "دربی پایتخت با گزارش تصویری و تحلیل کارشناسان",
    thumbnail: "/assets/images/png/test.jpg",
    category: "ورزشی",
    categorySlug: "sports",
    startTime: new Date(Date.now() + 1000 * 60 * 30).toISOString(),
    isLive: false,
    viewers: 0,
  },
  {
    id: "live-3",
    title: "رونمایی از محصول جدید شرکت فناوری ایرانی",
    description: "معرفی جدیدترین دستاوردهای فناوری داخلی",
    thumbnail: "/assets/images/png/test.jpg",
    category: "فناوری",
    categorySlug: "tech",
    startTime: new Date().toISOString(),
    isLive: true,
    viewers: 3280,
  },
  {
    id: "live-4",
    title: "تحلیل لحظه‌ای بازار بورس و اقتصاد",
    description: "بررسی روند بازار سهام و پیش‌بینی روزهای آینده",
    thumbnail: "/assets/images/png/test.jpg",
    category: "اقتصادی",
    categorySlug: "economy",
    startTime: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    isLive: true,
    viewers: 5670,
  },
];

export const mockArchivedStreams: ArchivedStream[] = [
  {
    id: "archive-1",
    title: "مصاحبه اختصاصی با وزیر اقتصاد",
    description: "گفتگوی جامع درباره سیاست‌های اقتصادی دولت و برنامه‌های آینده",
    thumbnail: "/assets/images/png/test.jpg",
    category: "اقتصادی",
    categorySlug: "economy",
    recordedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    duration: 45,
    views: 8920,
  },
  {
    id: "archive-2",
    title: "خلاصه بازی فینال جام حذفی",
    description: "گلها و لحظات حساس دیدار فینال جام حذفی فوتبال ایران",
    thumbnail: "/assets/images/png/test.jpg",
    category: "ورزشی",
    categorySlug: "sports",
    recordedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    duration: 12,
    views: 25400,
  },
  {
    id: "archive-3",
    title: "نمایشگاه فناوری و نوآوری تهران",
    description: "گزارش تصویری از جدیدترین محصولات فناوری در نمایشگاه",
    thumbnail: "/assets/images/png/test.jpg",
    category: "فناوری",
    categorySlug: "tech",
    recordedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    duration: 38,
    views: 6750,
  },
  {
    id: "archive-4",
    title: "مراسم افتتاح نیروگاه خورشیدی یزد",
    description:
      "پوشش کامل مراسم بهره‌برداری از بزرگ‌ترین نیروگاه خورشیدی کشور",
    thumbnail: "/assets/images/png/test.jpg",
    category: "علم",
    categorySlug: "science",
    recordedAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    duration: 28,
    views: 4320,
  },
  {
    id: "archive-5",
    title: "گفتگو با کارگردان برنده جایزه جشنواره",
    description: "مصاحبه با سازنده فیلم برنده جایزه بهترین فیلم",
    thumbnail: "/assets/images/png/test.jpg",
    category: "سینما",
    categorySlug: "cinema",
    recordedAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    duration: 52,
    views: 11200,
  },
  {
    id: "archive-6",
    title: "نشست تخصصی درباره دیابت و سلامت",
    description: "سخنرانی متخصصان درباره پیشگیری و درمان دیابت",
    thumbnail: "/assets/images/png/test.jpg",
    category: "سلامت",
    categorySlug: "health",
    recordedAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    duration: 65,
    views: 3890,
  },
];
